import { colors, radii, space, type } from '@atiraui/foundations/tokens.stylex'
import * as stylex from '@stylexjs/stylex'

export const galleryStyles = stylex.create({
  introduction: {
    display: 'flex',
    flexDirection: 'column',
    gap: space.x4,
    maxInlineSize: '48rem',
  },
  libraryTitle: {
    fontSize: { default: '1.75rem', '@media (min-width: 48rem)': '2.25rem' },
    fontWeight: type.weightStrong,
    lineHeight: '1.15',
    letterSpacing: '-0.035em',
    margin: 0,
    maxInlineSize: '24ch',
    textWrap: 'balance',
  },
  libraryDescription: {
    color: colors.textMuted,
    fontSize: type.sizeInput,
    lineHeight: type.lineBody,
    margin: 0,
    maxInlineSize: '58ch',
  },
  inlineLink: {
    color: colors.text,
    textUnderlineOffset: '3px',
    outlineColor: { default: 'transparent', ':focus-visible': colors.focus },
    outlineOffset: '3px',
    outlineStyle: 'solid',
    outlineWidth: '3px',
  },
  installGuide: {
    display: 'flex',
    flexDirection: 'column',
    gap: space.x6,
    minInlineSize: 0,
    padding: space.x4,
  },
  categoryNav: {
    backgroundColor: colors.canvas,
    insetBlockStart: 0,
    position: 'sticky',
    zIndex: 10,
  },
  categoryNavInner: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: space.x1,
    marginInline: 'auto',
    maxInlineSize: '68rem',
    paddingInline: {
      default: space.x4,
      '@media (min-width: 48rem)': space.x6,
    },
  },
  categoryLink: {
    alignItems: 'center',
    borderRadius: radii.control,
    color: colors.textMuted,
    display: 'inline-flex',
    flexShrink: 0,
    fontSize: type.sizeSmall,
    lineHeight: type.lineCompact,
    minBlockSize: {
      default: '2.25rem',
      '@media (hover: none)': '2.75rem',
    },
    outlineColor: { default: 'transparent', ':focus-visible': colors.focus },
    outlineStyle: 'solid',
    outlineWidth: '3px',
    paddingInline: space.x2,
    textDecoration: 'none',
    touchAction: 'manipulation',
    backgroundColor: {
      default: 'transparent',
      ':hover': {
        default: null,
        '@media (hover: hover) and (pointer: fine)': colors.surfaceHover,
      },
    },
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4rem',
    marginInline: 'auto',
    maxInlineSize: '68rem',
    paddingBlock: 0,
    paddingInline: {
      default: space.x4,
      '@media (min-width: 48rem)': space.x6,
    },
  },
  group: {
    borderBlockStartColor: colors.border,
    borderBlockStartStyle: 'solid',
    borderBlockStartWidth: '1px',
    display: 'flex',
    flexDirection: 'column',
    gap: space.x6,
    paddingBlockStart: space.x6,
    scrollMarginBlockStart: {
      default: '6.5rem',
      '@media (min-width: 48rem)': '3.5rem',
    },
  },
  groupHeading: {
    display: 'flex',
    flexDirection: 'column',
    gap: space.x1,
  },
  groupTitle: {
    fontSize: type.sizeHeading,
    fontWeight: type.weightStrong,
    lineHeight: type.lineHeading,
    margin: 0,
  },
  groupDescription: {
    color: colors.textMuted,
    fontSize: type.sizeSmall,
    lineHeight: type.lineBody,
    margin: 0,
    maxInlineSize: '65ch',
  },
  grid: {
    display: 'flex',
    flexDirection: 'column',
  },
  sample: {
    borderBlockStartColor: colors.border,
    borderBlockStartStyle: 'solid',
    borderBlockStartWidth: '1px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: space.x5,
    minInlineSize: 0,
    outlineColor: { default: 'transparent', ':focus-visible': colors.focus },
    outlineOffset: '3px',
    outlineStyle: 'solid',
    outlineWidth: '3px',
    paddingBlock: space.x8,
    scrollMarginBlockStart: space.x6,
  },
  sampleHeading: {
    display: 'flex',
    flexDirection: 'column',
    gap: space.x2,
  },
  sampleTitle: {
    fontSize: type.sizeHeading,
    fontWeight: type.weightStrong,
    lineHeight: type.lineHeading,
    margin: 0,
  },
  sampleDescription: {
    color: colors.textMuted,
    fontSize: type.sizeSmall,
    lineHeight: type.lineBody,
    margin: 0,
    maxInlineSize: '65ch',
  },
  apiNotes: {
    color: colors.textMuted,
    display: 'flex',
    flexWrap: 'wrap',
    fontSize: type.sizeCaption,
    gap: space.x2,
    lineHeight: type.lineBody,
    margin: 0,
    maxInlineSize: '72ch',
  },
  apiLabel: {
    color: colors.text,
    fontFamily: type.familyMono,
    fontWeight: type.weightMedium,
  },
  preview: {
    backgroundColor: colors.surface,
    borderRadius: radii.surface,
    boxShadow: 'var(--example-shadow)',
    display: 'flex',
    flexDirection: 'column',
    gap: space.x3,
    justifyContent: 'flex-start',
    minBlockSize: '9.5rem',
    minInlineSize: 0,
    overflow: 'hidden',
    padding: {
      default: space.x4,
      '@media (min-width: 48rem)': space.x5,
    },
  },
  previewWide: {
    minBlockSize: '10rem',
  },
  controls: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: space.x1,
    justifyContent: 'center',
  },
  actionFeedback: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: space.x2,
  },
  sampleStatus: {
    color: colors.textMuted,
    fontSize: type.sizeCaption,
    lineHeight: type.lineBody,
    margin: 0,
    textAlign: 'center',
  },
  artifactPreview: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: space.x2,
  },
  artifactImage: {
    backgroundColor: colors.surfaceMuted,
    borderColor: colors.border,
    borderRadius: radii.control,
    borderStyle: 'solid',
    borderWidth: '1px',
    boxSizing: 'border-box',
    color: colors.text,
    display: 'block',
    inlineSize: '100%',
    maxInlineSize: '20rem',
  },
  artifactTitle: {
    fill: colors.text,
    fontFamily: type.family,
    fontSize: type.sizeInput,
    fontWeight: type.weightStrong,
  },
  artifactDivider: {
    stroke: colors.border,
    strokeWidth: '1px',
  },
  artifactCard: {
    fill: colors.surface,
    stroke: colors.border,
    strokeWidth: '1px',
  },
  artifactPrimary: {
    fill: colors.accent,
  },
  artifactPrimaryLabel: {
    fill: colors.onAccent,
    fontFamily: type.family,
    fontSize: type.sizeCaption,
    fontWeight: type.weightMedium,
  },
  artifactSecondary: {
    fill: colors.surfaceSelected,
  },
  artifactSecondaryLabel: {
    fill: colors.text,
    fontFamily: type.family,
    fontSize: type.sizeCaption,
    fontWeight: type.weightMedium,
  },
  note: {
    color: colors.textMuted,
    fontSize: type.sizeSmall,
    lineHeight: type.lineBody,
    margin: 0,
  },
  stack: {
    display: 'flex',
    flexDirection: 'column',
    gap: space.x3,
  },
})
